version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
    command:
      - scripts/start_app.sh
    ports:
      - "8000:8000"
  
  database:
    image: "postgres" 
    env_file:
      - database.env 
    volumes:
      - database-data:/var/lib/postgresql/data/ 

volumes:
    database-data: 